const colaboradores = [
  { nome: "Matheus Nunes", setor: "TI", hardware: "", foto: "logo.esquadromil.branca.png", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } },
  { nome: "", setor: "", hardware: "", foto: "", teams: "", chamados: { Janeiro: 0, Fevereiro: 0 } }
];


